# ...existing code...
# Valores específicos para el entorno de desarrollo (overrides para Helm)
app:
  name: delivery                         # Nombre de la aplicación / etiqueta usada en recursos Kubernetes
  namespace: delivery-app-dev            # Namespace donde se desplegará en desarrollo
  image:
    repository: andrea233/delivery-system # Repositorio de la imagen Docker de la aplicación
    tag: "latest"                        # Tag de la imagen a usar en desarrollo
  replicas: 2                            # Número de réplicas del Deployment en dev
  port: 3000                             # Puerto interno donde escucha la aplicación en el contenedor
  service:
    port: 80                             # Puerto expuesto por el Service dentro del clúster
  ingress:
    enabled: true                        # Habilita la creación del Ingress en entorno dev
    className: nginx                     # Clase/controlador de Ingress a usar (ej. nginx)
    host: "dev.delivery-app.local"       # Dominio/host que atenderá el Ingress en dev (configurar /etc/hosts o DNS)
    apiPath: /api(/|$)(.*)               # Ruta/regex para enrutar tráfico a la API del backend
    frontendPath: /delivery(/|$)(.*)     # Ruta/regex para enrutar tráfico al frontend
  resources:
    requests:
      cpu: "100m"                        # CPU solicitado por pod (reserva mínima para scheduler)
      memory: "500Mi"                    # Memoria solicitada por pod (reserva mínima)

global:
  db:
    enabled: true                        # Habilita el subchart/recursos de la base de datos en dev
    host: delivery-db-service            # Host/Service name donde se resolverá MySQL dentro del clúster
    port: "3306"                         # Puerto de MySQL (como string para consistencia con plantillas)
    dbName: delivery                     # Nombre de la base de datos a crear/usarse
    dbUser: user                         # Usuario por defecto para la base de datos (solo para dev)
    dbPassword: pass                     # Contraseña del usuario (no usar en texto plano en entornos reales)