app:
  name: delivery
  namespace: delivery-app-dev
  image:
    repository: andrea233/delivery-system
    tag: "latest"
  replicas: 2
  port: 3000
  service:
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: "dev.delivery-app.local"
    apiPath: /api(/|$)(.*)
    frontendPath: /delivery(/|$)(.*)
  resources:
    requests:
      cpu: "100m"
      memory: "500Mi"

global:
  db:
    enabled: true
    host: delivery-db-service
    port: "3306"
    dbName: delivery
    dbUser: user
    dbPassword: pass
