apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.db.secretName }}
type: Opaque
stringData:
  
  DB_USER: "{{ .Values.global.db.secret.dbUser }}"
  DB_PASSWORD: "{{ .Values.global.db.secret.dbPassword }}"
  MYSQL_ROOT_PASSWORD: "{{ .Values.global.db.secret.rootPassword }}"
